<?php
/**
 * Menú del dashboard — PORTABLE (versionado, viaja por git).
 * ============================================================================
 *  Es la parte de la config que NO cambia entre dev y producción: el mapa de
 *  módulos del legacy (qué está construido y qué falta). `config/system.php`
 *  (gitignored, con rutas/modo/admin_users por instalación) lo incluye con:
 *        'menu' => require __DIR__ . '/menu.php',
 *  Así el menú no hay que replicarlo a mano en cada deploy.
 *
 *  Tabstrip estilo legacy: cada clave = una SOLAPA (tab); su valor = lista de
 *  tarjetas (en orden). Tipos de entrada:
 *    ['head' => 'LISTADOS']                         → sub-encabezado (no clickeable)
 *    ['label'=>..,'desc'=>..,'icon'=>..,'url'=>..]  → opción construida (link)
 *    ['label'=>'Cierre', 'disabled'=>true]          → opción del legacy aún NO portada
 *                                                      (gris, badge "pronto", no clickeable)
 *    ['label'=>..,'url'=>..,'admin'=>true]          → solo visible para admins (admin_users)
 *  El contador de la solapa muestra construidos/total cuando hay 'disabled'.
 * ============================================================================
 *
 * Orden = solapas del legacy (Access): IC, Stock, Acreedores, Deudores, Resumen, Varios.
 * Producción y Sucursales se omiten (vacías en el legacy). IVA Ventas va en Deudores e
 * IVA Compras en Varios, como en el legacy (no hay solapa IVA aparte).
 */

return [
    'Imputaciones Contables' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Bancos', 'disabled' => true],
        ['label' => 'Operaciones', 'disabled' => true],
        ['label' => 'Cuentas Bancarias', 'disabled' => true],
        ['label' => 'Centros de Costo', 'disabled' => true],
        ['label' => 'Cuentas Contables', 'disabled' => true],
        ['label' => 'Imputaciones Contables', 'desc' => 'Asientos contables: manuales, cheques (cartera/propio/diferido) y OP Contado con IVA', 'icon' => 'bi-journal-text', 'url' => '/modules/asientos/'],
        ['head' => 'Procesos'],
        ['label' => 'Conciliación', 'disabled' => true],
        ['label' => 'Cierre', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Bancos', 'desc' => 'Movimientos y conciliación bancaria', 'icon' => 'bi-bank', 'url' => '/modules/bancos/'],
        ['label' => 'Operaciones', 'disabled' => true],
        ['label' => 'Cuentas Bancarias', 'disabled' => true],
        ['label' => 'Centros de Costo', 'disabled' => true],
        ['label' => 'Plan de Cuentas', 'desc' => 'Cuentas contables (jerarquía)', 'icon' => 'bi-diagram-3', 'url' => '/modules/plan_cuentas/'],
        ['label' => 'Saldos Actuales', 'disabled' => true],
        ['label' => 'Saldos Periódicos', 'disabled' => true],
        ['label' => 'Balance de Sumas y Saldos', 'desc' => 'Balance contable por período', 'icon' => 'bi-table', 'url' => '/modules/balance/'],
        ['label' => 'Movimientos Cheques', 'disabled' => true],
        ['label' => 'Movimientos Bancarios', 'disabled' => true],
        ['label' => 'Pre-Conciliación', 'disabled' => true],
        ['label' => 'Valores a Depositar', 'disabled' => true],
        ['label' => 'Cheques Diferidos a Devengar', 'disabled' => true],
        ['label' => 'Parte Diario de Caja', 'disabled' => true],
        ['head' => 'Imputaciones Contables'],
        ['label' => 'x Operación', 'disabled' => true],
        ['label' => 'x Cuenta', 'desc' => 'Mayor por cuenta y período (Fec.Mov/Com)', 'icon' => 'bi-book', 'url' => '/modules/mayor/'],
        ['head' => 'Gastos'],
        ['label' => 'x Fecha Movimiento', 'disabled' => true],
        ['label' => 'x Fecha Comprobante', 'disabled' => true],
        ['head' => 'Gastos Extraordinarios'],
        ['label' => 'x Fecha Movimiento', 'disabled' => true],
        ['label' => 'x Fecha Comprobante', 'disabled' => true],
    ],
    'Stock' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Rubros', 'disabled' => true],
        ['label' => 'Líneas', 'disabled' => true],
        ['label' => 'Unidades de Medida', 'disabled' => true],
        ['label' => 'Productos', 'disabled' => true],
        ['label' => 'Ajustes', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Rubros', 'disabled' => true],
        ['label' => 'Líneas', 'disabled' => true],
        ['label' => 'Unidades de Medida', 'disabled' => true],
        ['label' => 'Stocks Mínimos', 'disabled' => true],
        ['label' => 'Precios de Venta', 'disabled' => true],
        ['label' => 'Exclusiones', 'disabled' => true],
        ['label' => 'Reposiciones', 'disabled' => true],
        ['head' => 'Productos'],
        ['label' => 'x Código', 'disabled' => true],
        ['label' => 'x Denominación', 'disabled' => true],
        ['label' => 'x Nivel', 'disabled' => true],
        ['head' => 'Movimientos'],
        ['label' => 'x Producto', 'disabled' => true],
        ['head' => 'Inventario'],
        ['label' => 'Actual', 'disabled' => true],
        ['label' => 'Periódico', 'disabled' => true],
    ],
    'Acreedores' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Cuentas Corrientes', 'disabled' => true],
        ['label' => 'Remitos', 'desc' => 'Mercadería recibida del proveedor (entrada de stock)', 'icon' => 'bi-box-arrow-in-down', 'url' => '/modules/remitos_acr/'],
        ['label' => 'Comprobantes a Pagar', 'desc' => 'Registrar factura del proveedor (gasto/servicio)', 'icon' => 'bi-receipt-cutoff', 'url' => '/modules/comprobantes_pagar/'],
        ['label' => 'Notas de Crédito', 'desc' => 'NC del proveedor (ajuste de cuenta corriente · sin AFIP)', 'icon' => 'bi-file-earmark-minus', 'url' => '/modules/notas_credito_acr/'],
        ['label' => 'Notas de Débito', 'desc' => 'ND del proveedor (debita la cta cte · referencia comprobantes · sin AFIP)', 'icon' => 'bi-file-earmark-plus', 'url' => '/modules/notas_debito_acr/'],
        ['label' => 'Órdenes de Pago', 'desc' => 'Pago a proveedores (cancelación)', 'icon' => 'bi-cash-stack', 'url' => '/modules/ordenes_pago/'],
        ['label' => 'Cancelación de Anticipos', 'disabled' => true],
        ['head' => 'Procesos'],
        ['label' => 'Export. Quincenal Ag.Rec. IIBB - Retenciones', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Cuentas Corrientes', 'disabled' => true],
        ['label' => 'Resumen de Cuenta', 'desc' => 'Cuenta corriente de proveedores', 'icon' => 'bi-journal-text', 'url' => '/modules/resumen_cuenta_acr/'],
        ['label' => 'Saldos Operaciones', 'disabled' => true],
        ['label' => 'Remitos Pendientes', 'disabled' => true],
        ['head' => 'Saldos'],
        ['label' => 'Actuales', 'desc' => 'A quién le debo (blanco/capacitación/total)', 'icon' => 'bi-cash-stack', 'url' => '/modules/saldos_actuales_acr/'],
        ['label' => 'Periódicos', 'disabled' => true],
        ['label' => 'Históricos', 'disabled' => true],
    ],
    'Deudores' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Categorías', 'desc' => 'Categorías de cuentas corrientes (deudores)', 'icon' => 'bi-tags', 'url' => '/modules/abm/?m=cat_deudores'],
        ['label' => 'Transportes', 'disabled' => true],
        ['label' => 'Vendedores', 'disabled' => true],
        ['label' => 'Zonas', 'disabled' => true],
        ['label' => 'Cuentas Corrientes', 'disabled' => true],
        ['label' => 'Formas de Pago Cta.Cte.', 'disabled' => true],
        ['label' => 'Operaciones Pendientes de Facturación', 'disabled' => true],
        ['head' => 'Emisiones'],
        ['label' => 'Remitos', 'desc' => 'Emisión de remitos a clientes', 'icon' => 'bi-truck', 'url' => '/modules/remitos/'],
        ['label' => 'Facturas', 'desc' => 'Emisión de facturas (electrónica · CAE AFIP)', 'icon' => 'bi-receipt', 'url' => '/modules/facturas/'],
        ['label' => 'Notas de Débito', 'desc' => 'Emisión de notas de débito (electrónica · CAE AFIP)', 'icon' => 'bi-file-earmark-plus', 'url' => '/modules/notas_debito/'],
        ['label' => 'Notas de Crédito', 'desc' => 'Emisión de notas de crédito (electrónica · CAE AFIP)', 'icon' => 'bi-file-earmark-minus', 'url' => '/modules/notas_credito/'],
        ['label' => 'Recibos', 'desc' => 'Cobranzas (cancelación de comprobantes)', 'icon' => 'bi-receipt', 'url' => '/modules/recibos/'],
        ['head' => 'Procesos'],
        ['label' => 'Export. Mensual Ag.Rec. IIBB - Percepciones Dev.', 'disabled' => true],
        ['label' => 'Export. Retenciones Ingresos Brutos', 'disabled' => true],
        ['label' => 'Export. Retenciones I.V.A.', 'disabled' => true],
        ['label' => 'Export. Retenciones Ganancias', 'disabled' => true],
        ['label' => 'Export. Retenciones S.U.S.S.', 'disabled' => true],
        ['label' => 'Export. I.V.A. Ventas a Holistor', 'desc' => 'Genera el .txt de IVA Ventas para importar en Holistor', 'icon' => 'bi-file-earmark-arrow-up', 'url' => '/modules/holistor_iva_ventas/'],
        ['head' => 'Listados'],
        ['label' => 'Categorías', 'disabled' => true],
        ['label' => 'Transportes', 'disabled' => true],
        ['label' => 'Vendedores', 'disabled' => true],
        ['label' => 'Zonas', 'disabled' => true],
        ['label' => 'Resumen de Cuenta', 'desc' => 'Cuenta corriente de clientes', 'icon' => 'bi-journal-text', 'url' => '/modules/resumen_cuenta/'],
        ['label' => 'Saldos Operaciones', 'disabled' => true],
        ['label' => 'I.V.A. Ventas', 'desc' => 'Libro IVA Ventas por período', 'icon' => 'bi-percent', 'url' => '/modules/iva_ventas/'],
        ['label' => 'Operaciones Pendientes de Facturación', 'disabled' => true],
        ['head' => 'Cuentas Corrientes'],
        ['label' => 'x Categoría', 'disabled' => true],
        ['label' => 'x Condición de Venta', 'disabled' => true],
        ['label' => 'x Denominación', 'disabled' => true],
        ['label' => 'x Localidad', 'disabled' => true],
        ['label' => 'x Vendedor', 'disabled' => true],
        ['label' => 'x Zona', 'disabled' => true],
        ['head' => 'Saldos'],
        ['label' => 'Actuales', 'desc' => 'Quién me debe (blanco/capacitación/total)', 'icon' => 'bi-cash-stack', 'url' => '/modules/saldos_actuales/'],
        ['label' => 'Periódicos', 'disabled' => true],
        ['label' => 'Históricos', 'disabled' => true],
    ],
    'Resumen' => [
        ['head' => 'Listados'],
        ['label' => 'Movimientos de Caja x Fecha', 'disabled' => true],
        ['label' => 'Movimientos Deudores x Cuenta', 'disabled' => true],
        ['label' => 'Movimientos Acreedores x Cuenta', 'disabled' => true],
        ['label' => 'Ventas x Fecha', 'disabled' => true],
        ['label' => 'Saldos Operaciones Deudores Estadístico', 'disabled' => true],
        ['head' => 'Cheques de Terceros'],
        ['label' => 'x Fecha de Acreditación', 'desc' => 'Cheques de terceros ordenados por acreditación', 'icon' => 'bi-cash-coin', 'url' => '/modules/cheques/?orden=acred'],
        ['label' => 'x Fecha de Entrada', 'desc' => 'Cheques de terceros ordenados por emisión/entrada', 'icon' => 'bi-cash-coin', 'url' => '/modules/cheques/?orden=entrada'],
        ['head' => 'Consultas (versión web)'],
        ['label' => 'Búsqueda de Comprobantes', 'desc' => 'Buscar facturas, recibos, NC/ND, etc.', 'icon' => 'bi-search', 'url' => '/modules/comprobantes/'],
    ],
    'Varios' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Localidades', 'desc' => 'Alta/edición de localidades', 'icon' => 'bi-geo-alt', 'url' => '/modules/abm/?m=localidades'],
        ['label' => 'Usuarios', 'disabled' => true],
        ['label' => 'Claves de Acceso', 'disabled' => true],
        ['label' => 'Período de Control', 'disabled' => true],
        ['label' => 'Período Predeterminado en Listados', 'disabled' => true],
        ['label' => 'Tipos de Movimientos Holistor', 'disabled' => true],
        ['head' => 'Procesos'],
        ['label' => 'Cotización u$s', 'disabled' => true],
        ['label' => 'Exportación Percepciones I.V.A. [Compras]', 'disabled' => true],
        ['label' => 'Exportación Percepciones IIBB [Compras]', 'disabled' => true],
        ['label' => 'Importación Padrón Contribuyentes IIBB Bs As', 'disabled' => true],
        ['label' => 'Cambio de Alícuota Padrón IIBB Bs As', 'disabled' => true],
        ['label' => 'Exportación I.V.A. Compras a Holistor', 'desc' => 'Genera el .txt de IVA Compras para importar en Holistor + mapeo cuenta→tipo', 'icon' => 'bi-file-earmark-arrow-down', 'url' => '/modules/holistor_iva_compras/'],
        ['label' => 'Cambio Fecha de Apertura', 'disabled' => true],
        ['label' => 'Modificación de Fecha Comprobante', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Localidades', 'disabled' => true],
        ['label' => 'Usuarios', 'disabled' => true],
        ['label' => 'I.V.A. Compras', 'desc' => 'Libro IVA Compras por período', 'icon' => 'bi-percent', 'url' => '/modules/iva_compras/'],
        ['head' => 'Reporte Contable'],
        ['label' => 'Stock e Inventario', 'disabled' => true],
        ['label' => 'Resultados Financieros y Estado Patrimonial', 'disabled' => true],
        ['label' => 'Imputaciones', 'disabled' => true],
        ['label' => 'P.P.P.', 'disabled' => true],
        ['head' => 'Sistema (versión web)'],
        ['label' => 'Pendientes de CAE', 'desc' => 'Comprobantes electrónicos sin CAE (AFIP caído) + reintento', 'icon' => 'bi-hourglass-split', 'url' => '/modules/cae_pendientes/'],
        ['label' => 'Estadísticas de Uso', 'desc' => 'Adopción: páginas, usuarios y máquinas', 'icon' => 'bi-graph-up-arrow', 'url' => '/modules/uso/', 'admin' => true],
    ],
];
