<?php
/**
 * Menú del dashboard — PORTABLE (versionado, viaja por git).
 * ============================================================================
 *  Es la parte de la config que NO cambia entre dev y producción: el mapa de
 *  módulos del legacy (qué está construido y qué falta). `config/system.php`
 *  (gitignored, con rutas/modo/admin_users por instalación) lo incluye con:
 *        'menu' => require __DIR__ . '/menu.php',
 *  Así el menú no hay que replicarlo a mano en cada deploy.
 *
 *  Tabstrip estilo legacy: cada clave = una SOLAPA (tab); su valor = lista de
 *  tarjetas (en orden). Tipos de entrada:
 *    ['head' => 'LISTADOS']                         → sub-encabezado (no clickeable)
 *    ['label'=>..,'desc'=>..,'icon'=>..,'url'=>..]  → opción construida (link)
 *    ['label'=>'Cierre', 'disabled'=>true]          → opción del legacy aún NO portada
 *                                                      (gris, badge "pronto", no clickeable)
 *    ['label'=>..,'url'=>..,'admin'=>true]          → solo visible para admins (admin_users)
 *  El contador de la solapa muestra construidos/total cuando hay 'disabled'.
 *
 *  'opt' => 'optXX' = OPTMEN de [Tbl Menu] del legacy. Habilita la RESTRICCIÓN por usuario
 *  (lista negra [Tbl Usuarios Menu]): si el usuario tiene esa opción cargada, no la ve ni
 *  accede por URL (ver includes/auth.php → auth_opt_denied / auth_gate_url, porta rutAccesoUsuario).
 *  Las entradas SIN 'opt' (extras web sin equivalente legacy) nunca se restringen.
 * ============================================================================
 *
 * Orden = solapas del legacy (Access): IC, Stock, Acreedores, Deudores, Resumen, Varios.
 * Producción y Sucursales se omiten (vacías en el legacy). IVA Ventas va en Deudores e
 * IVA Compras en Varios, como en el legacy (no hay solapa IVA aparte).
 */

return [
    'Imputaciones Contables' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Bancos', 'desc' => 'Alta/edición de bancos (denominación, CUIT)', 'icon' => 'bi-bank', 'url' => '/modules/abm/?m=bancos', 'opt' => 'optIC010'],
        ['label' => 'Operaciones', 'desc' => 'Config de operaciones (solo lectura): modelos de imputación, comprobantes', 'icon' => 'bi-gear-wide-connected', 'url' => '/modules/operaciones/', 'opt' => 'optIC020'],
        ['label' => 'Cuentas Bancarias', 'desc' => 'Cuentas bancarias (banco, copias de constancia)', 'icon' => 'bi-piggy-bank', 'url' => '/modules/abm/?m=cuentas_bancarias', 'opt' => 'optIC030'],
        ['label' => 'Centros de Costo', 'desc' => 'Alta/edición de centros de costo', 'icon' => 'bi-diagram-3', 'url' => '/modules/abm/?m=centros_costo', 'opt' => 'optIC040'],
        ['label' => 'Cuentas Contables', 'desc' => 'Plan de cuentas: alta/edición jerárquica, flags, saldos', 'icon' => 'bi-diagram-3', 'url' => '/modules/cuentas_contables/', 'opt' => 'optIC050'],
        ['label' => 'Imputaciones Contables', 'desc' => 'Asientos contables: manuales, cheques (cartera/propio/diferido) y OP Contado con IVA', 'icon' => 'bi-journal-text', 'url' => '/modules/asientos/', 'opt' => 'optIC060'],
        ['head' => 'Procesos'],
        ['label' => 'Conciliación', 'desc' => 'Conciliación bancaria: marca movimientos conciliados hasta una fecha de corte', 'icon' => 'bi-bank', 'url' => '/modules/conciliacion/', 'opt' => 'optIC100'],
        ['label' => 'Cierre', 'desc' => 'Cierre diario de caja: posición de efectivo/cheques + cambio de fecha del sistema', 'icon' => 'bi-cash-coin', 'url' => '/modules/cierre/', 'opt' => 'optIC110'],
        ['head' => 'Listados'],
        ['label' => 'Bancos', 'desc' => 'Listado del maestro de bancos (denominación, CUIT, código) — imprimible', 'icon' => 'bi-bank', 'url' => '/modules/list_bancos/', 'opt' => 'optIC300'],
        ['label' => 'Movimientos Bancarios', 'desc' => 'Ledger de una cuenta bancaria + estado de conciliación', 'icon' => 'bi-cash-stack', 'url' => '/modules/bancos/', 'opt' => 'optIC450'],
        ['label' => 'Operaciones', 'desc' => 'Listado de operaciones: comprobante, auxiliares y modelos de imputación — imprimible', 'icon' => 'bi-gear-wide-connected', 'url' => '/modules/list_operaciones/', 'opt' => 'optIC310'],
        ['label' => 'Cuentas Bancarias', 'desc' => 'Listado de cuentas bancarias (copias de constancia, discontinuada) — imprimible', 'icon' => 'bi-bank2', 'url' => '/modules/list_cuentas_bancarias/', 'opt' => 'optIC320'],
        ['label' => 'Centros de Costo', 'desc' => 'Listado de centros de costo — imprimible', 'icon' => 'bi-diagram-3', 'url' => '/modules/list_centros/', 'opt' => 'optIC330'],
        ['label' => 'Plan de Cuentas', 'desc' => 'Plan de cuentas jerárquico con flags y cuenta bancaria — imprimible', 'icon' => 'bi-list-nested', 'url' => '/modules/list_plan_cuentas/', 'opt' => 'optIC340'],
        ['label' => 'Plan de Cuentas (consulta)', 'desc' => 'Árbol de cuentas clickeable (→ mayor por cuenta)', 'icon' => 'bi-diagram-3', 'url' => '/modules/plan_cuentas/', 'opt' => 'optIC340'],
        ['label' => 'Saldos Actuales', 'desc' => 'Saldos actuales por cuenta (débitos/créditos/saldo + conciliación + totales) — imprimible', 'icon' => 'bi-clipboard-data', 'url' => '/modules/list_saldos/', 'opt' => 'optIC360'],
        ['label' => 'Saldos Periódicos', 'desc' => 'Saldos por cuenta acotados a un período (débitos/créditos/saldo + totales) — imprimible', 'icon' => 'bi-calendar-range', 'url' => '/modules/list_saldos_periodico/', 'opt' => 'Opción1443'],
        ['label' => 'Balance de Sumas y Saldos', 'desc' => 'Saldo anterior + débitos/créditos del período + saldo actual, por cuenta — imprimible', 'icon' => 'bi-journals', 'url' => '/modules/list_balance/', 'opt' => 'optIC350'],
        ['label' => 'Balance (consulta)', 'desc' => 'Balance interactivo por cuenta y período', 'icon' => 'bi-table', 'url' => '/modules/balance/', 'opt' => 'optIC350'],
        ['label' => 'Movimientos Cheques', 'desc' => 'Movimientos (debe/haber) por cheque: banco, librador, comprobante y cuenta — imprimible', 'icon' => 'bi-cash-coin', 'url' => '/modules/list_movim_cheques/', 'opt' => 'Opción1408'],
        ['label' => 'Movimientos Bancarios', 'desc' => 'Ledger por cuenta bancaria: saldo anterior + movimientos (debe/haber/saldo corrido) + subtotales — imprimible', 'icon' => 'bi-bank', 'url' => '/modules/list_movim_bancarios/', 'opt' => 'optIC450'],
        ['label' => 'Pre-Conciliación', 'desc' => 'Movimientos no conciliados por cuenta bancaria hasta una fecha (saldo corrido desde la última conciliación) — imprimible', 'icon' => 'bi-check2-square', 'url' => '/modules/list_pre_conciliacion/', 'opt' => 'Opción1410'],
        ['label' => 'Valores a Depositar', 'desc' => 'Cheques de terceros a depositar, por fecha de acreditación (año/mes/día) — imprimible', 'icon' => 'bi-cash-stack', 'url' => '/modules/list_cheques_fecha/?tipo=vad', 'opt' => 'optIC460'],
        ['label' => 'Cheques Diferidos a Devengar', 'desc' => 'Cheques diferidos por fecha de acreditación (año/mes/día) — imprimible', 'icon' => 'bi-calendar-check', 'url' => '/modules/list_cheques_fecha/?tipo=dif', 'opt' => 'Opción1574'],
        ['label' => 'Parte Diario de Caja', 'desc' => 'Caja del día: movimientos + cheques de terceros + cierre (efectivo/cheques) — imprimible', 'icon' => 'bi-cash-coin', 'url' => '/modules/list_parte_caja/', 'opt' => 'optIC470'],
        ['head' => 'Imputaciones Contables'],
        ['label' => 'x Operación', 'desc' => 'Movimientos agrupados por operación, con total por operación y período — imprimible', 'icon' => 'bi-journal-text', 'url' => '/modules/list_imput_operacion/', 'opt' => 'optIC400'],
        ['label' => 'x Cuenta [Fec. Mov.] Periódico', 'desc' => 'Mayor por rango de cuentas y período (por fecha de movimiento): operación, comprobante, cheque, centro, debe/haber/saldo — imprimible', 'icon' => 'bi-book', 'url' => '/modules/list_imput_cuenta/', 'opt' => 'optIC410'],
        ['label' => 'x Cuenta [Fec. Mov.] Histórico', 'desc' => 'Mayor por rango de cuentas hasta una fecha (histórico, por fecha de movimiento) — imprimible', 'icon' => 'bi-book', 'url' => '/modules/list_imput_cuenta/?hist=1', 'opt' => 'optIC410'],
        ['label' => 'x Cuenta [Fec. Com.] Periódico', 'desc' => 'Mayor por rango de cuentas y período (por fecha de comprobante) — imprimible', 'icon' => 'bi-book', 'url' => '/modules/list_imput_cuenta/?fecha=com', 'opt' => 'optIC410'],
        ['label' => 'x Cuenta [Fec. Com.] Histórico', 'desc' => 'Mayor por rango de cuentas hasta una fecha (histórico, por fecha de comprobante) — imprimible', 'icon' => 'bi-book', 'url' => '/modules/list_imput_cuenta/?fecha=com&hist=1', 'opt' => 'optIC410'],
        ['label' => 'x Cuenta (consulta)', 'desc' => 'Mayor interactivo por cuenta y período (Fec.Mov/Com)', 'icon' => 'bi-book', 'url' => '/modules/mayor/', 'opt' => 'optIC410'],
        ['head' => 'Gastos'],
        ['label' => 'x Fecha Movimiento', 'disabled' => true],
        ['label' => 'x Fecha Comprobante', 'disabled' => true],
        ['head' => 'Gastos Extraordinarios'],
        ['label' => 'x Fecha Movimiento', 'disabled' => true],
        ['label' => 'x Fecha Comprobante', 'disabled' => true],
    ],
    'Stock' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Rubros', 'desc' => 'Rubros + subform de Subrubros (cuentas contables compras/ventas, utilidad)', 'icon' => 'bi-tag', 'url' => '/modules/abm/?m=rubros', 'opt' => 'optSI020'],
        ['label' => 'Líneas', 'desc' => 'Alta/edición de líneas', 'icon' => 'bi-bookmark', 'url' => '/modules/abm/?m=lineas', 'opt' => 'optSI040'],
        ['label' => 'Unidades de Medida', 'desc' => 'Unidades de medida (decimales)', 'icon' => 'bi-rulers', 'url' => '/modules/abm/?m=unidades', 'opt' => 'optSI050'],
        ['label' => 'Productos', 'desc' => 'Productos y servicios: clasificación, precios, stock, equivalencias, proveedores', 'icon' => 'bi-box-seam', 'url' => '/modules/productos/', 'opt' => 'optSI070'],
        ['label' => 'Ajustes', 'desc' => 'Ajustes de stock: ingreso/egreso de existencias por concepto', 'icon' => 'bi-boxes', 'url' => '/modules/ajustes_stock/', 'opt' => 'optSI080'],
        ['head' => 'Listados'],
        ['label' => 'Rubros', 'disabled' => true],
        ['label' => 'Líneas', 'disabled' => true],
        ['label' => 'Unidades de Medida', 'disabled' => true],
        ['label' => 'Stocks Mínimos', 'disabled' => true],
        ['label' => 'Precios de Venta', 'disabled' => true],
        ['label' => 'Exclusiones', 'disabled' => true],
        ['label' => 'Reposiciones', 'disabled' => true],
        ['head' => 'Productos'],
        ['label' => 'x Código', 'disabled' => true],
        ['label' => 'x Denominación', 'disabled' => true],
        ['label' => 'x Nivel', 'disabled' => true],
        ['head' => 'Movimientos'],
        ['label' => 'x Producto', 'disabled' => true],
        ['head' => 'Inventario'],
        ['label' => 'Actual', 'disabled' => true],
        ['label' => 'Periódico', 'disabled' => true],
    ],
    'Acreedores' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Categorías', 'desc' => 'Categorías de cuentas corrientes (acreedores · alícuota IVA)', 'icon' => 'bi-tags', 'url' => '/modules/abm/?m=cat_acreedores'],
        ['label' => 'Cuentas Corrientes', 'desc' => 'Proveedores: datos, imputación de compras, percep/retención IIBB', 'icon' => 'bi-person-vcard', 'url' => '/modules/abm/?m=cc_acreedores', 'opt' => 'optCA010'],
        ['label' => 'Remitos', 'desc' => 'Mercadería recibida del proveedor (entrada de stock)', 'icon' => 'bi-box-arrow-in-down', 'url' => '/modules/remitos_acr/', 'opt' => 'optCA020'],
        ['label' => 'Comprobantes a Pagar', 'desc' => 'Registrar factura del proveedor (gasto/servicio)', 'icon' => 'bi-receipt-cutoff', 'url' => '/modules/comprobantes_pagar/', 'opt' => 'optCA030'],
        ['label' => 'Notas de Crédito', 'desc' => 'NC del proveedor (ajuste de cuenta corriente · sin AFIP)', 'icon' => 'bi-file-earmark-minus', 'url' => '/modules/notas_credito_acr/', 'opt' => 'optCA040'],
        ['label' => 'Notas de Débito', 'desc' => 'ND del proveedor (debita la cta cte · referencia comprobantes · sin AFIP)', 'icon' => 'bi-file-earmark-plus', 'url' => '/modules/notas_debito_acr/', 'opt' => 'optCA050'],
        ['label' => 'Órdenes de Pago', 'desc' => 'Pago a proveedores (cancelación)', 'icon' => 'bi-cash-stack', 'url' => '/modules/ordenes_pago/', 'opt' => 'optCA060'],
        ['label' => 'Cancelación de Anticipos', 'desc' => 'Aplica anticipos/acreditaciones del proveedor contra comprobantes pendientes', 'icon' => 'bi-arrow-left-right', 'url' => '/modules/cancelacion_anticipos/'],
        ['head' => 'Procesos'],
        ['label' => 'Export. Quincenal Ag.Rec. IIBB - Retenciones', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Cuentas Corrientes', 'disabled' => true],
        ['label' => 'Resumen de Cuenta', 'desc' => 'Cuenta corriente de proveedores', 'icon' => 'bi-journal-text', 'url' => '/modules/resumen_cuenta_acr/', 'opt' => 'optCA250'],
        ['label' => 'Saldos Operaciones', 'disabled' => true],
        ['label' => 'Remitos Pendientes', 'disabled' => true],
        ['head' => 'Saldos'],
        ['label' => 'Actuales', 'desc' => 'A quién le debo (blanco/capacitación/total)', 'icon' => 'bi-cash-stack', 'url' => '/modules/saldos_actuales_acr/', 'opt' => 'optCA210'],
        ['label' => 'Periódicos', 'disabled' => true],
        ['label' => 'Históricos', 'disabled' => true],
    ],
    'Deudores' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Categorías', 'desc' => 'Categorías de cuentas corrientes (deudores)', 'icon' => 'bi-tags', 'url' => '/modules/abm/?m=cat_deudores', 'opt' => 'Opción1438'],
        ['label' => 'Transportes', 'desc' => 'Alta/edición de transportes (CUIT, localidad, contacto)', 'icon' => 'bi-truck', 'url' => '/modules/abm/?m=transportes', 'opt' => 'Opción1236'],
        ['label' => 'Vendedores', 'desc' => 'Alta/edición de vendedores', 'icon' => 'bi-person-badge', 'url' => '/modules/abm/?m=vendedores', 'opt' => 'Opción1239'],
        ['label' => 'Zonas', 'desc' => 'Alta/edición de zonas', 'icon' => 'bi-geo', 'url' => '/modules/abm/?m=zonas', 'opt' => 'Opción1241'],
        ['label' => 'Cuentas Corrientes', 'desc' => 'Clientes: datos, categoría, condición de venta, saldos', 'icon' => 'bi-person-vcard', 'url' => '/modules/abm/?m=cc_deudores', 'opt' => 'Opción1243'],
        ['label' => 'Formas de Pago Cta.Cte.', 'desc' => 'Formas de pago de cuenta corriente (plazo en días)', 'icon' => 'bi-wallet2', 'url' => '/modules/abm/?m=formas_pago_ctacte', 'opt' => 'Opción1477'],
        ['label' => 'Operaciones Pendientes de Facturación', 'disabled' => true],
        ['head' => 'Emisiones'],
        ['label' => 'Remitos', 'desc' => 'Emisión de remitos a clientes', 'icon' => 'bi-truck', 'url' => '/modules/remitos/', 'opt' => 'optNF00'],
        ['label' => 'Facturas', 'desc' => 'Emisión de facturas (electrónica · CAE AFIP)', 'icon' => 'bi-receipt', 'url' => '/modules/facturas/', 'opt' => 'optNF01'],
        ['label' => 'Notas de Débito', 'desc' => 'Emisión de notas de débito (electrónica · CAE AFIP)', 'icon' => 'bi-file-earmark-plus', 'url' => '/modules/notas_debito/', 'opt' => 'optNF02'],
        ['label' => 'Notas de Crédito', 'desc' => 'Emisión de notas de crédito (electrónica · CAE AFIP)', 'icon' => 'bi-file-earmark-minus', 'url' => '/modules/notas_credito/', 'opt' => 'optNF03'],
        ['label' => 'Recibos', 'desc' => 'Cobranzas (cancelación de comprobantes)', 'icon' => 'bi-receipt', 'url' => '/modules/recibos/', 'opt' => 'optNF04'],
        ['head' => 'Procesos'],
        ['label' => 'Export. Mensual Ag.Rec. IIBB - Percepciones Dev.', 'disabled' => true],
        ['label' => 'Export. Retenciones Ingresos Brutos', 'disabled' => true],
        ['label' => 'Export. Retenciones I.V.A.', 'disabled' => true],
        ['label' => 'Export. Retenciones Ganancias', 'disabled' => true],
        ['label' => 'Export. Retenciones S.U.S.S.', 'disabled' => true],
        ['label' => 'Export. I.V.A. Ventas a Holistor', 'desc' => 'Genera el .txt de IVA Ventas para importar en Holistor', 'icon' => 'bi-file-earmark-arrow-up', 'url' => '/modules/holistor_iva_ventas/', 'opt' => 'Opción1639'],
        ['head' => 'Listados'],
        ['label' => 'Categorías', 'disabled' => true],
        ['label' => 'Transportes', 'disabled' => true],
        ['label' => 'Vendedores', 'disabled' => true],
        ['label' => 'Zonas', 'disabled' => true],
        ['label' => 'Resumen de Cuenta', 'desc' => 'Cuenta corriente de clientes', 'icon' => 'bi-journal-text', 'url' => '/modules/resumen_cuenta/', 'opt' => 'Opción1289'],
        ['label' => 'Saldos Operaciones', 'disabled' => true],
        ['label' => 'I.V.A. Ventas', 'desc' => 'Libro IVA Ventas por período', 'icon' => 'bi-percent', 'url' => '/modules/iva_ventas/', 'opt' => 'Opción1294'],
        ['label' => 'Operaciones Pendientes de Facturación', 'disabled' => true],
        ['head' => 'Cuentas Corrientes'],
        ['label' => 'x Categoría', 'disabled' => true],
        ['label' => 'x Condición de Venta', 'disabled' => true],
        ['label' => 'x Denominación', 'disabled' => true],
        ['label' => 'x Localidad', 'disabled' => true],
        ['label' => 'x Vendedor', 'disabled' => true],
        ['label' => 'x Zona', 'disabled' => true],
        ['head' => 'Saldos'],
        ['label' => 'Actuales', 'desc' => 'Quién me debe (blanco/capacitación/total)', 'icon' => 'bi-cash-stack', 'url' => '/modules/saldos_actuales/', 'opt' => 'Opción1280'],
        ['label' => 'Periódicos', 'disabled' => true],
        ['label' => 'Históricos', 'disabled' => true],
    ],
    'Resumen' => [
        ['head' => 'Listados'],
        ['label' => 'Movimientos de Caja x Fecha', 'disabled' => true],
        ['label' => 'Movimientos Deudores x Cuenta', 'disabled' => true],
        ['label' => 'Movimientos Acreedores x Cuenta', 'disabled' => true],
        ['label' => 'Ventas x Fecha', 'disabled' => true],
        ['label' => 'Saldos Operaciones Deudores Estadístico', 'disabled' => true],
        ['head' => 'Cheques de Terceros'],
        ['label' => 'x Fecha de Acreditación', 'desc' => 'Cheques de terceros ordenados por acreditación', 'icon' => 'bi-cash-coin', 'url' => '/modules/cheques/?orden=acred', 'opt' => 'Opción1608'],
        ['label' => 'x Fecha de Entrada', 'desc' => 'Cheques de terceros ordenados por emisión/entrada', 'icon' => 'bi-cash-coin', 'url' => '/modules/cheques/?orden=entrada', 'opt' => 'Opción1626'],
        ['head' => 'Consultas (versión web)'],
        ['label' => 'Búsqueda de Comprobantes', 'desc' => 'Buscar facturas, recibos, NC/ND, etc.', 'icon' => 'bi-search', 'url' => '/modules/comprobantes/'],
    ],
    'Varios' => [
        ['head' => 'Actualizaciones'],
        ['label' => 'Localidades', 'desc' => 'Alta/edición de localidades', 'icon' => 'bi-geo-alt', 'url' => '/modules/abm/?m=localidades', 'opt' => 'Opción1331'],
        ['label' => 'Usuarios', 'desc' => 'Usuarios: clave, categoría y restricciones de acceso (solo admin)', 'icon' => 'bi-people', 'url' => '/modules/abm/?m=usuarios', 'admin' => true, 'opt' => 'Opción1455'],
        ['label' => 'Claves de Acceso', 'disabled' => true],
        ['label' => 'Período de Control', 'disabled' => true],
        ['label' => 'Período Predeterminado en Listados', 'disabled' => true],
        ['label' => 'Tipos de Movimientos Holistor', 'desc' => 'Tipos de movimiento para exportación a Holistor (código + denominación)', 'icon' => 'bi-upc', 'url' => '/modules/abm/?m=holistor', 'opt' => 'Opción1645'],
        ['head' => 'Procesos'],
        ['label' => 'Cotización u$s', 'disabled' => true],
        ['label' => 'Exportación Percepciones I.V.A. [Compras]', 'disabled' => true],
        ['label' => 'Exportación Percepciones IIBB [Compras]', 'disabled' => true],
        ['label' => 'Importación Padrón Contribuyentes IIBB Bs As', 'disabled' => true],
        ['label' => 'Cambio de Alícuota Padrón IIBB Bs As', 'disabled' => true],
        ['label' => 'Exportación I.V.A. Compras a Holistor', 'desc' => 'Genera el .txt de IVA Compras para importar en Holistor + mapeo cuenta→tipo', 'icon' => 'bi-file-earmark-arrow-down', 'url' => '/modules/holistor_iva_compras/', 'opt' => 'Opción1637'],
        ['label' => 'Cambio Fecha de Apertura', 'disabled' => true],
        ['label' => 'Modificación de Fecha Comprobante', 'disabled' => true],
        ['head' => 'Listados'],
        ['label' => 'Localidades', 'disabled' => true],
        ['label' => 'Usuarios', 'disabled' => true],
        ['label' => 'I.V.A. Compras', 'desc' => 'Libro IVA Compras por período', 'icon' => 'bi-percent', 'url' => '/modules/iva_compras/', 'opt' => 'Opción1449'],
        ['head' => 'Reporte Contable'],
        ['label' => 'Stock e Inventario', 'disabled' => true],
        ['label' => 'Resultados Financieros y Estado Patrimonial', 'disabled' => true],
        ['label' => 'Imputaciones', 'disabled' => true],
        ['label' => 'P.P.P.', 'disabled' => true],
        ['head' => 'Sistema (versión web)'],
        ['label' => 'Pendientes de CAE', 'desc' => 'Comprobantes electrónicos sin CAE (AFIP caído) + reintento', 'icon' => 'bi-hourglass-split', 'url' => '/modules/cae_pendientes/'],
        ['label' => 'Estadísticas de Uso', 'desc' => 'Adopción: páginas, usuarios y máquinas', 'icon' => 'bi-graph-up-arrow', 'url' => '/modules/uso/', 'admin' => true],
        ['label' => 'Performance', 'desc' => 'Tiempos por módulo/query — detectar cuellos de botella y cuelgues', 'icon' => 'bi-speedometer2', 'url' => '/modules/perf/', 'admin' => true],
    ],
];
